export * from './always'
export * from './curryN'
export * from './curry'
export * from './allPass'
export * from './identity'
export * from './applyOrReturn'
export * from './both'
export * from './comparator'
export * from './complement'
export * from './compose'
export * from './cond'
export * from './debounce'

export * from './memoize/createCache'
export * from './memoize/with'
export * from './memoize/deep'
export * from './memoize/deepSizeLimit'
export * from './memoize/weak'
export * from './memoize/strictSingle'

import composeP from './composeP'
export {composeP}
